# Generated by Django 5.2.3 on 2025-06-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creeated_at',
            new_name='created_at',
        ),
    ]
